dino:
  head_n_prototypes: 131072
  head_bottleneck_dim: 384
ibot:
  separate_head: true
  head_n_prototypes: 131072
train:
  batch_size_per_gpu: 32
#official ImageNet22k
  dataset_path: TestDataset
  centering: sinkhorn_knopp
student:
  arch: vit_large
  patch_size: 14
  drop_path_rate: 0.4
  ffn_layer: swiglufused
  block_chunks: 4
  pretrained_weights: /home/liushy01/dinov2/1/dinov2_vitl14_reg4_pretrain.pth
teacher:
  momentum_teacher: 0.994
  pretrained_weights: /home/liushy01/dinov2/1/dinov2_vitl14_reg4_pretrain.pth
optim:
  epochs: 200
  weight_decay_end: 0.2
  base_lr: 6.25e-05  # learning rate for a batch size of 1024
  warmup_epochs: 40
  layerwise_decay: 1.0
  freeze_last_layer_epochs: 0
  freeze_backbone_layer_epochs: 20
crops:
  local_crops_size: 98
