dino:
  head_n_prototypes: 131072
  head_bottleneck_dim: 384
ibot:
  separate_head: true
  head_n_prototypes: 131072
train:
  batch_size_per_gpu: 2
  dataset_path: ImageNet22k
  centering: sinkhorn_knopp
student:
  arch: vit_giant2
  patch_size: 14
  drop_path_rate: 0.4
  ffn_layer: swiglufused
  block_chunks: 4
  pretrained_weights: '/home/liushy01/dinov2/1/teacher_checkpoint.pth'
teacher:
  momentum_teacher: 0.994
  pretrained_weights: /home/liushy01/dinov2/1/teacher_checkpoint.pth'
optim:
  epochs: 200
  weight_decay_end: 0.2
  base_lr: 0.625e-05  # learning rate for a batch size of 1024 is 2e-4
  warmup_epochs: 20
  layerwise_decay: 1.0
crops:
  local_crops_size: 98
  global_crops_size: 518
